;;;; up to 7 deep
(defmacro caar (x)
  `(car (car ,x)))
(defmacro cadr (x)
  `(car (cdr ,x)))
(defmacro cdar (x)
  `(cdr (car ,x)))
(defmacro cddr (x)
  `(cdr (cdr ,x)))
(defmacro caaar (x)
  `(car (car (car ,x))))
(defmacro caadr (x)
  `(car (car (cdr ,x))))
(defmacro cadar (x)
  `(car (cdr (car ,x))))
(defmacro caddr (x)
  `(car (cdr (cdr ,x))))
(defmacro cdaar (x)
  `(cdr (car (car ,x))))
(defmacro cdadr (x)
  `(cdr (car (cdr ,x))))
(defmacro cddar (x)
  `(cdr (cdr (car ,x))))
(defmacro cdddr (x)
  `(cdr (cdr (cdr ,x))))
#|
(defmacro caaaar (x)
  `(car (car (car (car ,x)))))
(defmacro caaadr (x)
  `(car (car (car (cdr ,x)))))
(defmacro caadar (x)
  `(car (car (cdr (car ,x)))))
(defmacro caaddr (x)
  `(car (car (cdr (cdr ,x)))))
(defmacro cadaar (x)
  `(car (cdr (car (car ,x)))))
(defmacro cadadr (x)
  `(car (cdr (car (cdr ,x)))))
(defmacro caddar (x)
  `(car (cdr (cdr (car ,x)))))
(defmacro cadddr (x)
  `(car (cdr (cdr (cdr ,x)))))
(defmacro cdaaar (x)
  `(cdr (car (car (car ,x)))))
(defmacro cdaadr (x)
  `(cdr (car (car (cdr ,x)))))
(defmacro cdadar (x)
  `(cdr (car (cdr (car ,x)))))
(defmacro cdaddr (x)
  `(cdr (car (cdr (cdr ,x)))))
(defmacro cddaar (x)
  `(cdr (cdr (car (car ,x)))))
(defmacro cddadr (x)
  `(cdr (cdr (car (cdr ,x)))))
(defmacro cdddar (x)
  `(cdr (cdr (cdr (car ,x)))))
(defmacro cddddr (x)
  `(cdr (cdr (cdr (cdr ,x)))))
(defmacro caaaaar (x)
  `(car (car (car (car (car ,x))))))
(defmacro caaaadr (x)
  `(car (car (car (car (cdr ,x))))))
(defmacro caaadar (x)
  `(car (car (car (cdr (car ,x))))))
(defmacro caaaddr (x)
  `(car (car (car (cdr (cdr ,x))))))
(defmacro caadaar (x)
  `(car (car (cdr (car (car ,x))))))
(defmacro caadadr (x)
  `(car (car (cdr (car (cdr ,x))))))
(defmacro caaddar (x)
  `(car (car (cdr (cdr (car ,x))))))
(defmacro caadddr (x)
  `(car (car (cdr (cdr (cdr ,x))))))
(defmacro cadaaar (x)
  `(car (cdr (car (car (car ,x))))))
(defmacro cadaadr (x)
  `(car (cdr (car (car (cdr ,x))))))
(defmacro cadadar (x)
  `(car (cdr (car (cdr (car ,x))))))
(defmacro cadaddr (x)
  `(car (cdr (car (cdr (cdr ,x))))))
(defmacro caddaar (x)
  `(car (cdr (cdr (car (car ,x))))))
(defmacro caddadr (x)
  `(car (cdr (cdr (car (cdr ,x))))))
(defmacro cadddar (x)
  `(car (cdr (cdr (cdr (car ,x))))))
(defmacro caddddr (x)
  `(car (cdr (cdr (cdr (cdr ,x))))))
(defmacro cdaaaar (x)
  `(cdr (car (car (car (car ,x))))))
(defmacro cdaaadr (x)
  `(cdr (car (car (car (cdr ,x))))))
(defmacro cdaadar (x)
  `(cdr (car (car (cdr (car ,x))))))
(defmacro cdaaddr (x)
  `(cdr (car (car (cdr (cdr ,x))))))
(defmacro cdadaar (x)
  `(cdr (car (cdr (car (car ,x))))))
(defmacro cdadadr (x)
  `(cdr (car (cdr (car (cdr ,x))))))
(defmacro cdaddar (x)
  `(cdr (car (cdr (cdr (car ,x))))))
(defmacro cdadddr (x)
  `(cdr (car (cdr (cdr (cdr ,x))))))
(defmacro cddaaar (x)
  `(cdr (cdr (car (car (car ,x))))))
(defmacro cddaadr (x)
  `(cdr (cdr (car (car (cdr ,x))))))
(defmacro cddadar (x)
  `(cdr (cdr (car (cdr (car ,x))))))
(defmacro cddaddr (x)
  `(cdr (cdr (car (cdr (cdr ,x))))))
(defmacro cdddaar (x)
  `(cdr (cdr (cdr (car (car ,x))))))
(defmacro cdddadr (x)
  `(cdr (cdr (cdr (car (cdr ,x))))))
(defmacro cddddar (x)
  `(cdr (cdr (cdr (cdr (car ,x))))))
(defmacro cdddddr (x)
  `(cdr (cdr (cdr (cdr (cdr ,x))))))
(defmacro caaaaaar (x)
  `(car (car (car (car (car (car ,x)))))))
(defmacro caaaaadr (x)
  `(car (car (car (car (car (cdr ,x)))))))
(defmacro caaaadar (x)
  `(car (car (car (car (cdr (car ,x)))))))
(defmacro caaaaddr (x)
  `(car (car (car (car (cdr (cdr ,x)))))))
(defmacro caaadaar (x)
  `(car (car (car (cdr (car (car ,x)))))))
(defmacro caaadadr (x)
  `(car (car (car (cdr (car (cdr ,x)))))))
(defmacro caaaddar (x)
  `(car (car (car (cdr (cdr (car ,x)))))))
(defmacro caaadddr (x)
  `(car (car (car (cdr (cdr (cdr ,x)))))))
(defmacro caadaaar (x)
  `(car (car (cdr (car (car (car ,x)))))))
(defmacro caadaadr (x)
  `(car (car (cdr (car (car (cdr ,x)))))))
(defmacro caadadar (x)
  `(car (car (cdr (car (cdr (car ,x)))))))
(defmacro caadaddr (x)
  `(car (car (cdr (car (cdr (cdr ,x)))))))
(defmacro caaddaar (x)
  `(car (car (cdr (cdr (car (car ,x)))))))
(defmacro caaddadr (x)
  `(car (car (cdr (cdr (car (cdr ,x)))))))
(defmacro caadddar (x)
  `(car (car (cdr (cdr (cdr (car ,x)))))))
(defmacro caaddddr (x)
  `(car (car (cdr (cdr (cdr (cdr ,x)))))))
(defmacro cadaaaar (x)
  `(car (cdr (car (car (car (car ,x)))))))
(defmacro cadaaadr (x)
  `(car (cdr (car (car (car (cdr ,x)))))))
(defmacro cadaadar (x)
  `(car (cdr (car (car (cdr (car ,x)))))))
(defmacro cadaaddr (x)
  `(car (cdr (car (car (cdr (cdr ,x)))))))
(defmacro cadadaar (x)
  `(car (cdr (car (cdr (car (car ,x)))))))
(defmacro cadadadr (x)
  `(car (cdr (car (cdr (car (cdr ,x)))))))
(defmacro cadaddar (x)
  `(car (cdr (car (cdr (cdr (car ,x)))))))
(defmacro cadadddr (x)
  `(car (cdr (car (cdr (cdr (cdr ,x)))))))
(defmacro caddaaar (x)
  `(car (cdr (cdr (car (car (car ,x)))))))
(defmacro caddaadr (x)
  `(car (cdr (cdr (car (car (cdr ,x)))))))
(defmacro caddadar (x)
  `(car (cdr (cdr (car (cdr (car ,x)))))))
(defmacro caddaddr (x)
  `(car (cdr (cdr (car (cdr (cdr ,x)))))))
(defmacro cadddaar (x)
  `(car (cdr (cdr (cdr (car (car ,x)))))))
(defmacro cadddadr (x)
  `(car (cdr (cdr (cdr (car (cdr ,x)))))))
(defmacro caddddar (x)
  `(car (cdr (cdr (cdr (cdr (car ,x)))))))
(defmacro cadddddr (x)
  `(car (cdr (cdr (cdr (cdr (cdr ,x)))))))
(defmacro cdaaaaar (x)
  `(cdr (car (car (car (car (car ,x)))))))
(defmacro cdaaaadr (x)
  `(cdr (car (car (car (car (cdr ,x)))))))
(defmacro cdaaadar (x)
  `(cdr (car (car (car (cdr (car ,x)))))))
(defmacro cdaaaddr (x)
  `(cdr (car (car (car (cdr (cdr ,x)))))))
(defmacro cdaadaar (x)
  `(cdr (car (car (cdr (car (car ,x)))))))
(defmacro cdaadadr (x)
  `(cdr (car (car (cdr (car (cdr ,x)))))))
(defmacro cdaaddar (x)
  `(cdr (car (car (cdr (cdr (car ,x)))))))
(defmacro cdaadddr (x)
  `(cdr (car (car (cdr (cdr (cdr ,x)))))))
(defmacro cdadaaar (x)
  `(cdr (car (cdr (car (car (car ,x)))))))
(defmacro cdadaadr (x)
  `(cdr (car (cdr (car (car (cdr ,x)))))))
(defmacro cdadadar (x)
  `(cdr (car (cdr (car (cdr (car ,x)))))))
(defmacro cdadaddr (x)
  `(cdr (car (cdr (car (cdr (cdr ,x)))))))
(defmacro cdaddaar (x)
  `(cdr (car (cdr (cdr (car (car ,x)))))))
(defmacro cdaddadr (x)
  `(cdr (car (cdr (cdr (car (cdr ,x)))))))
(defmacro cdadddar (x)
  `(cdr (car (cdr (cdr (cdr (car ,x)))))))
(defmacro cdaddddr (x)
  `(cdr (car (cdr (cdr (cdr (cdr ,x)))))))
(defmacro cddaaaar (x)
  `(cdr (cdr (car (car (car (car ,x)))))))
(defmacro cddaaadr (x)
  `(cdr (cdr (car (car (car (cdr ,x)))))))
(defmacro cddaadar (x)
  `(cdr (cdr (car (car (cdr (car ,x)))))))
(defmacro cddaaddr (x)
  `(cdr (cdr (car (car (cdr (cdr ,x)))))))
(defmacro cddadaar (x)
  `(cdr (cdr (car (cdr (car (car ,x)))))))
(defmacro cddadadr (x)
  `(cdr (cdr (car (cdr (car (cdr ,x)))))))
(defmacro cddaddar (x)
  `(cdr (cdr (car (cdr (cdr (car ,x)))))))
(defmacro cddadddr (x)
  `(cdr (cdr (car (cdr (cdr (cdr ,x)))))))
(defmacro cdddaaar (x)
  `(cdr (cdr (cdr (car (car (car ,x)))))))
(defmacro cdddaadr (x)
  `(cdr (cdr (cdr (car (car (cdr ,x)))))))
(defmacro cdddadar (x)
  `(cdr (cdr (cdr (car (cdr (car ,x)))))))
(defmacro cdddaddr (x)
  `(cdr (cdr (cdr (car (cdr (cdr ,x)))))))
(defmacro cddddaar (x)
  `(cdr (cdr (cdr (cdr (car (car ,x)))))))
(defmacro cddddadr (x)
  `(cdr (cdr (cdr (cdr (car (cdr ,x)))))))
(defmacro cdddddar (x)
  `(cdr (cdr (cdr (cdr (cdr (car ,x)))))))
(defmacro cddddddr (x)
  `(cdr (cdr (cdr (cdr (cdr (cdr ,x)))))))
(defmacro caaaaaaar (x)
  `(car (car (car (car (car (car (car ,x))))))))
(defmacro caaaaaadr (x)
  `(car (car (car (car (car (car (cdr ,x))))))))
(defmacro caaaaadar (x)
  `(car (car (car (car (car (cdr (car ,x))))))))
(defmacro caaaaaddr (x)
  `(car (car (car (car (car (cdr (cdr ,x))))))))
(defmacro caaaadaar (x)
  `(car (car (car (car (cdr (car (car ,x))))))))
(defmacro caaaadadr (x)
  `(car (car (car (car (cdr (car (cdr ,x))))))))
(defmacro caaaaddar (x)
  `(car (car (car (car (cdr (cdr (car ,x))))))))
(defmacro caaaadddr (x)
  `(car (car (car (car (cdr (cdr (cdr ,x))))))))
(defmacro caaadaaar (x)
  `(car (car (car (cdr (car (car (car ,x))))))))
(defmacro caaadaadr (x)
  `(car (car (car (cdr (car (car (cdr ,x))))))))
(defmacro caaadadar (x)
  `(car (car (car (cdr (car (cdr (car ,x))))))))
(defmacro caaadaddr (x)
  `(car (car (car (cdr (car (cdr (cdr ,x))))))))
(defmacro caaaddaar (x)
  `(car (car (car (cdr (cdr (car (car ,x))))))))
(defmacro caaaddadr (x)
  `(car (car (car (cdr (cdr (car (cdr ,x))))))))
(defmacro caaadddar (x)
  `(car (car (car (cdr (cdr (cdr (car ,x))))))))
(defmacro caaaddddr (x)
  `(car (car (car (cdr (cdr (cdr (cdr ,x))))))))
(defmacro caadaaaar (x)
  `(car (car (cdr (car (car (car (car ,x))))))))
(defmacro caadaaadr (x)
  `(car (car (cdr (car (car (car (cdr ,x))))))))
(defmacro caadaadar (x)
  `(car (car (cdr (car (car (cdr (car ,x))))))))
(defmacro caadaaddr (x)
  `(car (car (cdr (car (car (cdr (cdr ,x))))))))
(defmacro caadadaar (x)
  `(car (car (cdr (car (cdr (car (car ,x))))))))
(defmacro caadadadr (x)
  `(car (car (cdr (car (cdr (car (cdr ,x))))))))
(defmacro caadaddar (x)
  `(car (car (cdr (car (cdr (cdr (car ,x))))))))
(defmacro caadadddr (x)
  `(car (car (cdr (car (cdr (cdr (cdr ,x))))))))
(defmacro caaddaaar (x)
  `(car (car (cdr (cdr (car (car (car ,x))))))))
(defmacro caaddaadr (x)
  `(car (car (cdr (cdr (car (car (cdr ,x))))))))
(defmacro caaddadar (x)
  `(car (car (cdr (cdr (car (cdr (car ,x))))))))
(defmacro caaddaddr (x)
  `(car (car (cdr (cdr (car (cdr (cdr ,x))))))))
(defmacro caadddaar (x)
  `(car (car (cdr (cdr (cdr (car (car ,x))))))))
(defmacro caadddadr (x)
  `(car (car (cdr (cdr (cdr (car (cdr ,x))))))))
(defmacro caaddddar (x)
  `(car (car (cdr (cdr (cdr (cdr (car ,x))))))))
(defmacro caadddddr (x)
  `(car (car (cdr (cdr (cdr (cdr (cdr ,x))))))))
(defmacro cadaaaaar (x)
  `(car (cdr (car (car (car (car (car ,x))))))))
(defmacro cadaaaadr (x)
  `(car (cdr (car (car (car (car (cdr ,x))))))))
(defmacro cadaaadar (x)
  `(car (cdr (car (car (car (cdr (car ,x))))))))
(defmacro cadaaaddr (x)
  `(car (cdr (car (car (car (cdr (cdr ,x))))))))
(defmacro cadaadaar (x)
  `(car (cdr (car (car (cdr (car (car ,x))))))))
(defmacro cadaadadr (x)
  `(car (cdr (car (car (cdr (car (cdr ,x))))))))
(defmacro cadaaddar (x)
  `(car (cdr (car (car (cdr (cdr (car ,x))))))))
(defmacro cadaadddr (x)
  `(car (cdr (car (car (cdr (cdr (cdr ,x))))))))
(defmacro cadadaaar (x)
  `(car (cdr (car (cdr (car (car (car ,x))))))))
(defmacro cadadaadr (x)
  `(car (cdr (car (cdr (car (car (cdr ,x))))))))
(defmacro cadadadar (x)
  `(car (cdr (car (cdr (car (cdr (car ,x))))))))
(defmacro cadadaddr (x)
  `(car (cdr (car (cdr (car (cdr (cdr ,x))))))))
(defmacro cadaddaar (x)
  `(car (cdr (car (cdr (cdr (car (car ,x))))))))
(defmacro cadaddadr (x)
  `(car (cdr (car (cdr (cdr (car (cdr ,x))))))))
(defmacro cadadddar (x)
  `(car (cdr (car (cdr (cdr (cdr (car ,x))))))))
(defmacro cadaddddr (x)
  `(car (cdr (car (cdr (cdr (cdr (cdr ,x))))))))
(defmacro caddaaaar (x)
  `(car (cdr (cdr (car (car (car (car ,x))))))))
(defmacro caddaaadr (x)
  `(car (cdr (cdr (car (car (car (cdr ,x))))))))
(defmacro caddaadar (x)
  `(car (cdr (cdr (car (car (cdr (car ,x))))))))
(defmacro caddaaddr (x)
  `(car (cdr (cdr (car (car (cdr (cdr ,x))))))))
(defmacro caddadaar (x)
  `(car (cdr (cdr (car (cdr (car (car ,x))))))))
(defmacro caddadadr (x)
  `(car (cdr (cdr (car (cdr (car (cdr ,x))))))))
(defmacro caddaddar (x)
  `(car (cdr (cdr (car (cdr (cdr (car ,x))))))))
(defmacro caddadddr (x)
  `(car (cdr (cdr (car (cdr (cdr (cdr ,x))))))))
(defmacro cadddaaar (x)
  `(car (cdr (cdr (cdr (car (car (car ,x))))))))
(defmacro cadddaadr (x)
  `(car (cdr (cdr (cdr (car (car (cdr ,x))))))))
(defmacro cadddadar (x)
  `(car (cdr (cdr (cdr (car (cdr (car ,x))))))))
(defmacro cadddaddr (x)
  `(car (cdr (cdr (cdr (car (cdr (cdr ,x))))))))
(defmacro caddddaar (x)
  `(car (cdr (cdr (cdr (cdr (car (car ,x))))))))
(defmacro caddddadr (x)
  `(car (cdr (cdr (cdr (cdr (car (cdr ,x))))))))
(defmacro cadddddar (x)
  `(car (cdr (cdr (cdr (cdr (cdr (car ,x))))))))
(defmacro caddddddr (x)
  `(car (cdr (cdr (cdr (cdr (cdr (cdr ,x))))))))
(defmacro cdaaaaaar (x)
  `(cdr (car (car (car (car (car (car ,x))))))))
(defmacro cdaaaaadr (x)
  `(cdr (car (car (car (car (car (cdr ,x))))))))
(defmacro cdaaaadar (x)
  `(cdr (car (car (car (car (cdr (car ,x))))))))
(defmacro cdaaaaddr (x)
  `(cdr (car (car (car (car (cdr (cdr ,x))))))))
(defmacro cdaaadaar (x)
  `(cdr (car (car (car (cdr (car (car ,x))))))))
(defmacro cdaaadadr (x)
  `(cdr (car (car (car (cdr (car (cdr ,x))))))))
(defmacro cdaaaddar (x)
  `(cdr (car (car (car (cdr (cdr (car ,x))))))))
(defmacro cdaaadddr (x)
  `(cdr (car (car (car (cdr (cdr (cdr ,x))))))))
(defmacro cdaadaaar (x)
  `(cdr (car (car (cdr (car (car (car ,x))))))))
(defmacro cdaadaadr (x)
  `(cdr (car (car (cdr (car (car (cdr ,x))))))))
(defmacro cdaadadar (x)
  `(cdr (car (car (cdr (car (cdr (car ,x))))))))
(defmacro cdaadaddr (x)
  `(cdr (car (car (cdr (car (cdr (cdr ,x))))))))
(defmacro cdaaddaar (x)
  `(cdr (car (car (cdr (cdr (car (car ,x))))))))
(defmacro cdaaddadr (x)
  `(cdr (car (car (cdr (cdr (car (cdr ,x))))))))
(defmacro cdaadddar (x)
  `(cdr (car (car (cdr (cdr (cdr (car ,x))))))))
(defmacro cdaaddddr (x)
  `(cdr (car (car (cdr (cdr (cdr (cdr ,x))))))))
(defmacro cdadaaaar (x)
  `(cdr (car (cdr (car (car (car (car ,x))))))))
(defmacro cdadaaadr (x)
  `(cdr (car (cdr (car (car (car (cdr ,x))))))))
(defmacro cdadaadar (x)
  `(cdr (car (cdr (car (car (cdr (car ,x))))))))
(defmacro cdadaaddr (x)
  `(cdr (car (cdr (car (car (cdr (cdr ,x))))))))
(defmacro cdadadaar (x)
  `(cdr (car (cdr (car (cdr (car (car ,x))))))))
(defmacro cdadadadr (x)
  `(cdr (car (cdr (car (cdr (car (cdr ,x))))))))
(defmacro cdadaddar (x)
  `(cdr (car (cdr (car (cdr (cdr (car ,x))))))))
(defmacro cdadadddr (x)
  `(cdr (car (cdr (car (cdr (cdr (cdr ,x))))))))
(defmacro cdaddaaar (x)
  `(cdr (car (cdr (cdr (car (car (car ,x))))))))
(defmacro cdaddaadr (x)
  `(cdr (car (cdr (cdr (car (car (cdr ,x))))))))
(defmacro cdaddadar (x)
  `(cdr (car (cdr (cdr (car (cdr (car ,x))))))))
(defmacro cdaddaddr (x)
  `(cdr (car (cdr (cdr (car (cdr (cdr ,x))))))))
(defmacro cdadddaar (x)
  `(cdr (car (cdr (cdr (cdr (car (car ,x))))))))
(defmacro cdadddadr (x)
  `(cdr (car (cdr (cdr (cdr (car (cdr ,x))))))))
(defmacro cdaddddar (x)
  `(cdr (car (cdr (cdr (cdr (cdr (car ,x))))))))
(defmacro cdadddddr (x)
  `(cdr (car (cdr (cdr (cdr (cdr (cdr ,x))))))))
(defmacro cddaaaaar (x)
  `(cdr (cdr (car (car (car (car (car ,x))))))))
(defmacro cddaaaadr (x)
  `(cdr (cdr (car (car (car (car (cdr ,x))))))))
(defmacro cddaaadar (x)
  `(cdr (cdr (car (car (car (cdr (car ,x))))))))
(defmacro cddaaaddr (x)
  `(cdr (cdr (car (car (car (cdr (cdr ,x))))))))
(defmacro cddaadaar (x)
  `(cdr (cdr (car (car (cdr (car (car ,x))))))))
(defmacro cddaadadr (x)
  `(cdr (cdr (car (car (cdr (car (cdr ,x))))))))
(defmacro cddaaddar (x)
  `(cdr (cdr (car (car (cdr (cdr (car ,x))))))))
(defmacro cddaadddr (x)
  `(cdr (cdr (car (car (cdr (cdr (cdr ,x))))))))
(defmacro cddadaaar (x)
  `(cdr (cdr (car (cdr (car (car (car ,x))))))))
(defmacro cddadaadr (x)
  `(cdr (cdr (car (cdr (car (car (cdr ,x))))))))
(defmacro cddadadar (x)
  `(cdr (cdr (car (cdr (car (cdr (car ,x))))))))
(defmacro cddadaddr (x)
  `(cdr (cdr (car (cdr (car (cdr (cdr ,x))))))))
(defmacro cddaddaar (x)
  `(cdr (cdr (car (cdr (cdr (car (car ,x))))))))
(defmacro cddaddadr (x)
  `(cdr (cdr (car (cdr (cdr (car (cdr ,x))))))))
(defmacro cddadddar (x)
  `(cdr (cdr (car (cdr (cdr (cdr (car ,x))))))))
(defmacro cddaddddr (x)
  `(cdr (cdr (car (cdr (cdr (cdr (cdr ,x))))))))
(defmacro cdddaaaar (x)
  `(cdr (cdr (cdr (car (car (car (car ,x))))))))
(defmacro cdddaaadr (x)
  `(cdr (cdr (cdr (car (car (car (cdr ,x))))))))
(defmacro cdddaadar (x)
  `(cdr (cdr (cdr (car (car (cdr (car ,x))))))))
(defmacro cdddaaddr (x)
  `(cdr (cdr (cdr (car (car (cdr (cdr ,x))))))))
(defmacro cdddadaar (x)
  `(cdr (cdr (cdr (car (cdr (car (car ,x))))))))
(defmacro cdddadadr (x)
  `(cdr (cdr (cdr (car (cdr (car (cdr ,x))))))))
(defmacro cdddaddar (x)
  `(cdr (cdr (cdr (car (cdr (cdr (car ,x))))))))
(defmacro cdddadddr (x)
  `(cdr (cdr (cdr (car (cdr (cdr (cdr ,x))))))))
(defmacro cddddaaar (x)
  `(cdr (cdr (cdr (cdr (car (car (car ,x))))))))
(defmacro cddddaadr (x)
  `(cdr (cdr (cdr (cdr (car (car (cdr ,x))))))))
(defmacro cddddadar (x)
  `(cdr (cdr (cdr (cdr (car (cdr (car ,x))))))))
(defmacro cddddaddr (x)
  `(cdr (cdr (cdr (cdr (car (cdr (cdr ,x))))))))
(defmacro cdddddaar (x)
  `(cdr (cdr (cdr (cdr (cdr (car (car ,x))))))))
(defmacro cdddddadr (x)
  `(cdr (cdr (cdr (cdr (cdr (car (cdr ,x))))))))
(defmacro cddddddar (x)
  `(cdr (cdr (cdr (cdr (cdr (cdr (car ,x))))))))
(defmacro cdddddddr (x)
  `(cdr (cdr (cdr (cdr (cdr (cdr (cdr ,x))))))))

|#
